
name: Deploy D-Client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Clone D-Client
        run: git clone https://github.com/MoonSupport/dictionary-client.git
          

      - name: Generate output
        run: npm run deploy
        env:
          D_API: ${{ secrets.D_API }}

  